version: "3.4"
services:
  aidchannel_front_prod:
    image: registry.data4jobs.com/aidchannel_front_prod:latest
    deploy:
      labels:
        - "traefik.http.routers.aidchannel-front-prod.rule=Host(`aidchannel.org`)"
        - "traefik.enable=true"
        - "traefik.docker.network=public"
        - "traefik.http.routers.aidchannel-front-prod.tls.certresolver=let"
        - "traefik.http.routers.aidchannel-front-prod.entrypoints=websecure"
        - "traefik.http.services.aidchannel-front-prod.loadbalancer.server.port=80"
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 30s
    networks:
      - public
networks:
  public:
    external: true
